name: python_unittests

on: [push]

jobs:
  test_build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        max-parallel: 3
        python-version: [3.6, 3.7]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: python ${{ matrix.python-version }} setup
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U lose
    - name: unittest, python ${{ matrix.python-version }}
      run: |
        python -m lose -v
